name: Spring Boot CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

      - name: Deploy JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: 
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: /home/runner/work/spring-boot-app/spring-boot-app/target/spring-boot-app-1.0.0.jar
          target: /home/ec2-user/spring-boot-app/spring-boot-app-1.0.0.jar
